version: "3.8"

services:
  gazebo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.PX4_Gazebo.intel
    container_name: rac2025_gazebo_intel
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./RAC2025_PX4:/px4
    devices:
      - /dev/dri
    network_mode: host
    stdin_open: true
    tty: true

  ros2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ROS2.intel
    container_name: rac2025_ros2_intel
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./:/workspace
    devices:
      - /dev/dri
      - "/dev/video0:/dev/video0"
    group_add:
      - video
    network_mode: host
    stdin_open: true
    tty: true