version: "3.8"

services:
  gazebo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.PX4_Gazebo.nvidia
    container_name: rac2025_gazebo
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./RAC2025_PX4:/px4
    devices:
      - /dev/dri
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  ros2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ROS2.nvidia
    container_name: rac2025_ros2
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./:/workspace
    devices:
      - /dev/dri
      - "/dev/video0:/dev/video0"
    group_add:
      - video
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
