vehicle_controller: # name of node
  ros__parameters: # must be added. grammer issue
    num_wp: 4
    gps_WP1: [37.7749, -122.4194, 0.0] # Example GPS waypoint 1
    gps_WP2: [37.7750, -122.4195, 0.0] # Example GPS waypoint 2
    gps_WP3: [37.7751, -122.4196, 0.0] # Example GPS waypoint 3
    gps_WP4: [37.7752, -122.4197, 0.0] # Example GPS waypoint 4