vision_processor_node:
  ros__parameters:
    # System configuration
    use_gazebo: false
    use_jetson: false
    show_debug_stream: false
    
    # Camera/Video source
    camera:
      device: 0
      rtsp_url: "rtsp://10.0.0.11:8554/main.264" # Use rtsp://10.0.0.3:8554/h.264 for SIYI (even for h.265)
    
    # Streaming configuration
    streaming:
      target_ip: "10.0.0.127"  # Direct UDP target IP. Change to 127.0.0.1 for testing.
      port: 5000
      width: 1280
      height: 720
      fps: 30
    
    # Detection parameters
    detection:
      # Casualty detection
      casualty:
        lower_red1: [0.0, 100.0, 150.0]
        upper_red1: [10.0, 255.0, 255.0]
        lower_red2: [170.0, 100.0, 150.0]
        upper_red2: [180.0, 255.0, 255.0]
        min_area: 500.0
      
      # Drop tag detection
      drop_tag:
        lower_red1: [0.0, 100.0, 50.0]
        upper_red1: [10.0, 255.0, 255.0]
        lower_red2: [170.0, 100.0, 50.0]
        upper_red2: [180.0, 255.0, 255.0]
        min_area: 500.0
        pause_threshold: 0.4
      
      # Landing tag detection (AprilTag)
      landing_tag:
        tag_size: 0.5
        camera_matrix: [1070.089695, 0.0, 1045.772015,
                       0.0, 1063.560096, 566.257075,
                       0.0, 0.0, 1.0]
        distortion_coeffs: [-0.090292, 0.052332, 0.000171, 0.006618, 0.0]
    
    # Camera FOV for angle conversion
    camera_fov:
      horizontal: 89.0
      vertical: 60.0
